### ISSUE TITLE
Some general thoughts on two of the roadmap questions

### ISSUE THREAD

**Issue by pipermerriam** [ConsenSys/live-libs#1]
* Should there be any way for any party to update a specific version of a library?
    * No.  Releases should be immutable.  Mutable releases introduce significant attack surface.
* How do we incorporate source code and documentation?
    * I would recommend adding an additional `mapping (bytes32 => string) resourceURIs` to each release.  This would allow people to register URIs for each release (eg: `"source" => "ipfs://abcdef"`).  (these should likely be immutable as well).

**Comment by redsquirrel** [comment]
> Releases should be immutable.

Agreed.

> How do we incorporate source code and documentation?

This is actually already answered. (I will update the wiki.) Each version has optional attributes to allow the author to provide URLs for source and docs. See: https://github.com/ConsenSys/live-libs/blob/master/contracts/LiveLibs.sol#L8

**Comment by pipermerriam** [comment]
I'm skeptical that `docURL` and `sourceURL` are going to be the appropriate abstractions.  Doesn't allow for additional links.  For example, I might include a `signatureURI` with my releases so that people can verify the signature against my public key.

Also, somewhat nit-pick but using the term `URI` is potentially more appropriate and covers a broader type of identifier.

**Comment by redsquirrel** [comment]
That all makes sense. Do you see any issue with a lib author being able to `setResource(libName, versionNum, key, uri)` and overwrite a previously set key? Or should key/values for resources be immutable? If mutable, I'd store an `NewResource` event in the log.

**Comment by pipermerriam** [comment]
I'd suggest some combination of the following

* Resource URIs should be immutable.  Makes it possible to cache them naively and if people need mutability they can do so via a secondary mechanism.
* A window of time during which resources can be registered, after which they are locked.
* An alternative to registering resources independently would be to include them in the call to `register`

`function register(bytes32 libName, uint versionNum, address a, string abi, string docURL, string sourceURL, uint thresholdWei, bytes32[] resourceKeys, string[] resourceURIs)`

Then you effectively zip up the keys and values, throwing if their lengths mismatch and insert them into the mapping.

**Comment by redsquirrel** [comment]
> `function register(bytes32 libName, uint versionNum, address a, string abi, uint thresholdWei, bytes32[] resourceKeys, string[] resourceURIs)`

This won't compile because Solidity can't handle `string[]` as input to functions. Unfortunately, it looks like each key/value will need to be sent separately.

Thanks for the feedback.

**Comment by pipermerriam** [comment]
> This won't compile because Solidity can't handle string[] as input to functions.

doh!

Ok, after more thinking, I think it is ok to allow registering resources after the fact as long as they are immutable once registered.  Thanks for making this btw.  I spent a decent amount of time trying to figure out how to integrate this with the `compile` features of `populus` so that it can auto-link libraries.

**Comment by redsquirrel** [comment]
I'm currently working on integrate this into the browser-soldity UI. Made good progress yesterday.

**Comment by redsquirrel** [comment]
https://github.com/ConsenSys/live-libs/commit/a11916113e4790b0e2f1e9d9dee25ed7506a3d48 implements @pipermerriam's resource suggestions.
